### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/Vault-Sample---Job4iLogicRuleExec#1]
Hello,

This is realy nice thing for Vault users and CAD administrator.

This solution get file to user workspace, what is litle bit dangerous, because user can had some old version of file on his local drive. It will be good if file and workspace can be at some temp folder.

**Comment by koechlm** [comment]
The job intentionally implemented using the working folder for job execution instead of a temporary folder. A job processor is expected to run on a dedicated machine. Therefore the importance of working with the latest files is a priority. The job's framework is prepared to run jobs in a different folder, however, the cleanup of these locations isn't.
Chime in discussing this topic here in case you agree or disagree.

**Comment by koechlm** [comment]
Let's split the logging issue into a separate issue thread, please.

**Comment by DariuszMrozik** [comment]
I know, that JobProcessror should work on dedicated server machine, but that requirement is expensive for some customers with 3-4 CAD licenses. They always have JobProcessor on designer computers. 

In our experience , we always get files to temp folder (in JobProcessor extension and in VaultPro Client extension).

**Comment by koechlm** [comment]
Thank you again for the feedback. Much appreciated. Sure, it could make sense to add a configuration option running in default (Vault configured) working folder or a job-specific temporary one. Will add as New Feature request and gather more feedback from channel and field.
