### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/Vault-Sample---Job4iLogicRuleExec#3]
There is also some problem on polish version with loging. Extension working for me if i comment this line: // mLogCtrl.SaveLogAs(mILogicLogFileFullName);

image
![image](https://user-images.githubusercontent.com/61918020/76197342-41108800-61ec-11ea-8e49-05f0c7d7a0d9.png)

In another case I'm geting exception:"
Job failed by unhandled exception: System.InvalidOperationException: Brak aktualnego pliku dziennika.
w System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
w CallSite.Target(Closure , CallSite , ComObject , String )
w System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
w System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
w Autodesk.VltInvSrv.iLogicSampleJob.JobExtension.Execute(IJobProcessorServices context, IJob job) w C:\Users\koechlm\source\Autodesk.VltInvSrv.iLogicSampleJob\Autodesk.VltInvSrv.iLogicSampleJob\JobExtension.cs:wiersz 471
"

**Comment by koechlm** [comment]
Thank you for this report. Did you try on an EN operating system as well? So, I am eager to drill down the issue and the first question is: is this related to the non-English OS in general. Did you configure as mentioned in the Readme? If you don't copy the config file, the logging will crash on English OS as well. Please check and confirm. Thanks,
Markus

**Comment by DariuszMrozik** [comment]
@koechlm i didn't try it on EN OS. Do you mean copy setting.xml to extension folder? Yes I copied it to VAult Extension folder and configure it. If You want, we can make remote session.

**Comment by koechlm** [comment]
No, to enable logging you need to copy the file iLogicLogger.config to the VaultInventorServer.exe location: C:\Program Files\Autodesk\Vault Professional 2020\Explorer\Inventor Server\Bin.
I am sure, this is the root cause and after that, you should be able to uncomment the line. At least a good point for an installer ;).

**Comment by DariuszMrozik** [comment]
Thank You, I didn't note that.

It will be good to have an installer exe. Look at this software:
https://jrsoftware.org/isinfo.php

**Comment by koechlm** [comment]
@DariuszMrozik: Did you give it another try with the config file copied to the right location?
Thanks,
Markus

**Comment by DariuszMrozik** [comment]
Yes, it was working for me after your information. Are you going to prepare an installer for this vault customisation? If you need, I can show you, how to make it easy with InoSetup via remote session.

**Comment by koechlm** [comment]
Hi Dariusz,
Glad to hear that it turned out well. And thank you for your offer to get me started quickly with the InnoSetup tool. I might come back, once the new version (includes Administration UI and your wishlist item to interactively select a rule and submit to queue like PDF) is fully tested. If you are interested in this immediately, the latest commit covers all.
Cheers, and stay sane!
Markus
