### ISSUE TITLE
Empty BombBlob

### ISSUE THREAD

**Issue by GioCauzzi89** [koechlm/Vault-Sample---Job4iLogicRuleExec#34]
**Describe the bug**
When the job archives the files the Bom Blob is empty.
This leads us to have 2 types of vault errors when we launch the "Assign/update item" command:
1. The file does not contain the item data
2. Error 1455

**To Reproduce**
1. Uses a file already linked to an article
2. Run Ilogic Job so that the IPT file is opened, saved and checked in
3. Do "assign/update item"

**Expected behavior**
I shouldn't have these errors and the BombBlob should compile

**Screenshots**
![Empy BomBlob](https://github.com/koechlm/Vault-Job-Processor---iLogic-Extension/assets/134497861/109223ac-333f-407d-a069-02ae86bb5a8a)

![Error 1455](https://github.com/koechlm/Vault-Job-Processor---iLogic-Extension/assets/134497861/190f0c3d-0e2a-46a3-b308-f338503e092b)

**Comment by koechlm** [comment]
The behavior is as intended: The job extension sample uses VaultInventorServer. InventorServer does not support Vault check-in and FileBom (BomBlob) creation. Therefore, it is intentional, that assembly files are checked-in with the BOM object removed. So, users are forced to open and re-check in the assembly with full Inventor. Compare removing the parent BOM in the Vault copy design, it works similarly.
To check in assemblies with BOM, the job extension would require a full Inventor calling the Inventor-Vault Check-In command. The sources are open and you are free to extend it. Using full Inventor is already implemented and is an option in the setup of user-submitted job definition. The missing piece is extending/changing the code to check in using the Inventor command manager. An alternate approach is to leverage the job extension to handle the assembly files read-only but write a rule that does everything from check out to check in within full Inventor.
